server:
  port: 8082
  
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

spring:
  data:
    mongodb:
      database: db_address
      port: 27017
      host: localhost
mq:
  queue:
    event-notification: event-notification